# Generated by Django 5.1.1 on 2024-10-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
