# Generated by Django 5.1.1 on 2024-10-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('user', '0004_alter_booking_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('normal_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.normaluser')),
            ],
            bases=('authtoken.token',),
        ),
    ]
